// AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.
import type { Activity } from "@/lib/types";
import { reservedActivities } from "./lanes/reserved";
import { pcActivities } from "./lanes/pc";
import { cfActivities } from "./lanes/cf";
import { pclActivities } from "./lanes/pcl";
import { fpActivities } from "./lanes/fp";
import { rcActivities } from "./lanes/rc";
import { stActivities } from "./lanes/st";
import { igActivities } from "./lanes/ig";
import { iaActivities } from "./lanes/ia";
import { ogActivities } from "./lanes/og";
import { tbActivities } from "./lanes/tb";
import { waActivities } from "./lanes/wa";
import { sqActivities } from "./lanes/sq";
import { ssActivities } from "./lanes/ss";
import { th1Activities } from "./lanes/th1";
import { th2Activities } from "./lanes/th2";
import { sciActivities } from "./lanes/sci";

export const SEED_ACTIVITIES: Activity[] = [
  ...reservedActivities,
  ...pcActivities,
  ...cfActivities,
  ...pclActivities,
  ...fpActivities,
  ...rcActivities,
  ...stActivities,
  ...igActivities,
  ...iaActivities,
  ...ogActivities,
  ...tbActivities,
  ...waActivities,
  ...sqActivities,
  ...ssActivities,
  ...th1Activities,
  ...th2Activities,
  ...sciActivities,
];
