// AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.
import type { Activity } from "@/lib/types";
import { reservedActivities } from "./lanes/reserved";
import { kgActivities } from "./lanes/kg";
import { kcActivities } from "./lanes/kc";
import { roActivities } from "./lanes/ro";
import { rmActivities } from "./lanes/rm";
import { pcActivities } from "./lanes/pc";
import { cfActivities } from "./lanes/cf";
import { pclActivities } from "./lanes/pcl";
import { fpActivities } from "./lanes/fp";
import { rcActivities } from "./lanes/rc";
import { stActivities } from "./lanes/st";
import { igActivities } from "./lanes/ig";
import { iaActivities } from "./lanes/ia";
import { ogActivities } from "./lanes/og";
import { tbActivities } from "./lanes/tb";
import { waActivities } from "./lanes/wa";
import { sqActivities } from "./lanes/sq";
import { ssActivities } from "./lanes/ss";
import { th1Activities } from "./lanes/th1";
import { th2Activities } from "./lanes/th2";
import { sciActivities } from "./lanes/sci";
import { cpActivities } from "./lanes/cp";
import { cnActivities } from "./lanes/cn";
import { cyActivities } from "./lanes/cy";
import { cmActivities } from "./lanes/cm";
import { cdActivities } from "./lanes/cd";
import { cwActivities } from "./lanes/cw";
import { gtActivities } from "./lanes/gt";
import { gpActivities } from "./lanes/gp";
import { grActivities } from "./lanes/gr";
import { gbActivities } from "./lanes/gb";
import { gmActivities } from "./lanes/gm";
import { qmActivities } from "./lanes/qm";
import { qjActivities } from "./lanes/qj";
import { qoActivities } from "./lanes/qo";
import { wrActivities } from "./lanes/wr";
import { wtActivities } from "./lanes/wt";
import { wsActivities } from "./lanes/ws";
import { sgActivities } from "./lanes/sg";
import { smActivities } from "./lanes/sm";
import { srActivities } from "./lanes/sr";

export const SEED_ACTIVITIES: Activity[] = [
  ...reservedActivities,
  ...kgActivities,
  ...kcActivities,
  ...roActivities,
  ...rmActivities,
  ...pcActivities,
  ...cfActivities,
  ...pclActivities,
  ...fpActivities,
  ...rcActivities,
  ...stActivities,
  ...igActivities,
  ...iaActivities,
  ...ogActivities,
  ...tbActivities,
  ...waActivities,
  ...sqActivities,
  ...ssActivities,
  ...th1Activities,
  ...th2Activities,
  ...sciActivities,
  ...cpActivities,
  ...cnActivities,
  ...cyActivities,
  ...cmActivities,
  ...cdActivities,
  ...cwActivities,
  ...gtActivities,
  ...gpActivities,
  ...grActivities,
  ...gbActivities,
  ...gmActivities,
  ...qmActivities,
  ...qjActivities,
  ...qoActivities,
  ...wrActivities,
  ...wtActivities,
  ...wsActivities,
  ...sgActivities,
  ...smActivities,
  ...srActivities,
];
